name: FoodMoment
options:
  bundleIdPrefix: com.zhaochaoqun
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: BXQ44LYC44
    CODE_SIGN_STYLE: Automatic

configFiles:
  Debug: {}
  Release: {}

schemes:
  FoodMoment:
    build:
      targets:
        FoodMoment: all
        FoodMomentTests: [test]
        FoodMomentUITests: [test]
    run:
      config: Debug
      executable: FoodMoment
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - FoodMoment
      targets:
        - FoodMomentTests
        - FoodMomentUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  FoodMomentWidget-CalorieRing:
    build:
      targets:
        FoodMomentWidgetExtension: all
    run:
      config: Debug
      executable: FoodMomentWidgetExtension
      environmentVariables:
        _XCWidgetKind: CalorieRingWidget

  FoodMomentWidget-QuickScan:
    build:
      targets:
        FoodMomentWidgetExtension: all
    run:
      config: Debug
      executable: FoodMomentWidgetExtension
      environmentVariables:
        _XCWidgetKind: QuickScanWidget

targets:
  FoodMoment:
    type: application
    platform: iOS
    sources:
      - path: FoodMoment
        excludes:
          - "Resources/Info.plist"
      - path: FoodMoment/Resources/Assets.xcassets
        buildPhase: resources
    entitlements:
      path: FoodMoment/FoodMoment.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.background-delivery: true
        com.apple.security.application-groups:
          - group.com.zhaochaoqun.FoodMoment
    info:
      path: FoodMoment/Resources/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleURLTypes:
          - CFBundleURLName: com.zhaochaoqun.FoodMoment
            CFBundleURLSchemes:
              - foodmoment
        NSHealthShareUsageDescription: "FoodMoment needs access to read your health data to track steps and weight."
        NSHealthUpdateUsageDescription: "FoodMoment needs access to save nutrition, water intake, and weight data."
        NSCameraUsageDescription: "FoodMoment uses camera to scan and identify food for calorie tracking."
        NSPhotoLibraryUsageDescription: "FoodMoment needs access to your photo library to select food images."
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - fetch
          - processing
    settings:
      base:
        INFOPLIST_FILE: FoodMoment/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: com.zhaochaoqun.FoodMoment
        SWIFT_EMIT_LOC_STRINGS: "YES"
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - sdk: AuthenticationServices.framework
      - sdk: HealthKit.framework
      - sdk: WidgetKit.framework
      - sdk: CoreSpotlight.framework
      - target: FoodMomentWidgetExtension

  FoodMomentWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: FoodMomentWidget
        excludes:
          - "**/*.plist"
    resources:
      - path: FoodMomentWidget/Assets.xcassets
    entitlements:
      path: FoodMomentWidget/FoodMomentWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.zhaochaoqun.FoodMoment
    info:
      path: FoodMomentWidget/Info.plist
      properties:
        CFBundleDisplayName: FoodMoment Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zhaochaoqun.FoodMoment.widget
        TARGETED_DEVICE_FAMILY: "1"
        SKIP_INSTALL: "YES"
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework

  FoodMomentTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FoodMomentTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zhaochaoqun.FoodMoment.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FoodMoment.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FoodMoment"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: FoodMoment

  FoodMomentUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FoodMomentUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zhaochaoqun.FoodMoment.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_TARGET_NAME: FoodMoment
    dependencies:
      - target: FoodMoment
